// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: map/v1/daemon.proto

package mapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitTaskRequest creates a new task
type SubmitTaskRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ScopePaths  []string               `protobuf:"bytes,2,rep,name=scope_paths,json=scopePaths,proto3" json:"scope_paths,omitempty"`
	// Optional: target specific agent
	TargetAgentId string `protobuf:"bytes,3,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	// Optional: GitHub issue source tracking
	GithubOwner       string `protobuf:"bytes,4,opt,name=github_owner,json=githubOwner,proto3" json:"github_owner,omitempty"`
	GithubRepo        string `protobuf:"bytes,5,opt,name=github_repo,json=githubRepo,proto3" json:"github_repo,omitempty"`
	GithubIssueNumber int32  `protobuf:"varint,6,opt,name=github_issue_number,json=githubIssueNumber,proto3" json:"github_issue_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubmitTaskRequest) GetScopePaths() []string {
	if x != nil {
		return x.ScopePaths
	}
	return nil
}

func (x *SubmitTaskRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *SubmitTaskRequest) GetGithubOwner() string {
	if x != nil {
		return x.GithubOwner
	}
	return ""
}

func (x *SubmitTaskRequest) GetGithubRepo() string {
	if x != nil {
		return x.GithubRepo
	}
	return ""
}

func (x *SubmitTaskRequest) GetGithubIssueNumber() int32 {
	if x != nil {
		return x.GithubIssueNumber
	}
	return 0
}

// SubmitTaskResponse returns the created task
type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// ListTasksRequest filters for listing tasks
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by status
	StatusFilter TaskStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=map.v1.TaskStatus" json:"status_filter,omitempty"`
	// Optional filter by assigned agent
	AgentFilter string `protobuf:"bytes,2,opt,name=agent_filter,json=agentFilter,proto3" json:"agent_filter,omitempty"`
	// Limit number of results (0 = no limit)
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksRequest) GetStatusFilter() TaskStatus {
	if x != nil {
		return x.StatusFilter
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetAgentFilter() string {
	if x != nil {
		return x.AgentFilter
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListTasksResponse contains the list of tasks
type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// GetTaskRequest retrieves a specific task
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetTaskResponse returns the task details
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// CancelTaskRequest cancels a pending or in-progress task
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// CancelTaskResponse confirms task cancellation
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// ShutdownRequest asks the daemon to shut down
type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Force immediate shutdown without waiting for tasks
	Force         bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// ShutdownResponse confirms shutdown initiated
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetStatusRequest retrieves daemon status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{10}
}

// GetStatusResponse returns daemon status
type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Running         bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ConnectedAgents int32                  `protobuf:"varint,3,opt,name=connected_agents,json=connectedAgents,proto3" json:"connected_agents,omitempty"`
	PendingTasks    int32                  `protobuf:"varint,4,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	ActiveTasks     int32                  `protobuf:"varint,5,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetStatusResponse) GetConnectedAgents() int32 {
	if x != nil {
		return x.ConnectedAgents
	}
	return 0
}

func (x *GetStatusResponse) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *GetStatusResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

// WatchEventsRequest configures event streaming
type WatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by event types (empty = all events)
	TypeFilter []EventType `protobuf:"varint,1,rep,packed,name=type_filter,json=typeFilter,proto3,enum=map.v1.EventType" json:"type_filter,omitempty"`
	// Filter by agent ID
	AgentFilter string `protobuf:"bytes,2,opt,name=agent_filter,json=agentFilter,proto3" json:"agent_filter,omitempty"`
	// Filter by task ID
	TaskFilter    string `protobuf:"bytes,3,opt,name=task_filter,json=taskFilter,proto3" json:"task_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *WatchEventsRequest) GetTypeFilter() []EventType {
	if x != nil {
		return x.TypeFilter
	}
	return nil
}

func (x *WatchEventsRequest) GetAgentFilter() string {
	if x != nil {
		return x.AgentFilter
	}
	return ""
}

func (x *WatchEventsRequest) GetTaskFilter() string {
	if x != nil {
		return x.TaskFilter
	}
	return ""
}

// SpawnAgentRequest requests spawning Claude Code agents
type SpawnAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of agents to spawn (default: 1)
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Git branch for worktrees (empty = current branch)
	Branch string `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// Whether to create worktree isolation
	UseWorktree bool `protobuf:"varint,3,opt,name=use_worktree,json=useWorktree,proto3" json:"use_worktree,omitempty"`
	// Agent name prefix (default: "claude")
	NamePrefix string `protobuf:"bytes,4,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	// Initial prompt to send to Claude
	Prompt string `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Agent type: "claude" (default) or "codex"
	AgentType string `protobuf:"bytes,6,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	// Skip permission prompts so tasks execute immediately without user intervention
	// For claude: uses --dangerously-skip-permissions
	// For codex: uses --dangerously-bypass-approvals-and-sandbox
	// Default: true (agents work autonomously)
	SkipPermissions bool `protobuf:"varint,7,opt,name=skip_permissions,json=skipPermissions,proto3" json:"skip_permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SpawnAgentRequest) Reset() {
	*x = SpawnAgentRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentRequest) ProtoMessage() {}

func (x *SpawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentRequest.ProtoReflect.Descriptor instead.
func (*SpawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *SpawnAgentRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SpawnAgentRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SpawnAgentRequest) GetUseWorktree() bool {
	if x != nil {
		return x.UseWorktree
	}
	return false
}

func (x *SpawnAgentRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *SpawnAgentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SpawnAgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *SpawnAgentRequest) GetSkipPermissions() bool {
	if x != nil {
		return x.SkipPermissions
	}
	return false
}

// SpawnAgentResponse returns info about spawned agents
type SpawnAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*SpawnedAgentInfo    `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgentResponse) Reset() {
	*x = SpawnAgentResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgentResponse) ProtoMessage() {}

func (x *SpawnAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgentResponse.ProtoReflect.Descriptor instead.
func (*SpawnAgentResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *SpawnAgentResponse) GetAgents() []*SpawnedAgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// SpawnedAgentInfo describes a spawned agent
type SpawnedAgentInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorktreePath string                 `protobuf:"bytes,2,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	Pid          int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Status       string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LogFile      string                 `protobuf:"bytes,6,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	// Agent type: "claude" or "codex"
	AgentType     string `protobuf:"bytes,7,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnedAgentInfo) Reset() {
	*x = SpawnedAgentInfo{}
	mi := &file_map_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnedAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnedAgentInfo) ProtoMessage() {}

func (x *SpawnedAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnedAgentInfo.ProtoReflect.Descriptor instead.
func (*SpawnedAgentInfo) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *SpawnedAgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SpawnedAgentInfo) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

func (x *SpawnedAgentInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SpawnedAgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpawnedAgentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SpawnedAgentInfo) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *SpawnedAgentInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// KillAgentRequest requests termination of a spawned agent
type KillAgentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Force kill (SIGKILL instead of SIGTERM)
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillAgentRequest) Reset() {
	*x = KillAgentRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAgentRequest) ProtoMessage() {}

func (x *KillAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAgentRequest.ProtoReflect.Descriptor instead.
func (*KillAgentRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *KillAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *KillAgentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// KillAgentResponse confirms agent termination
type KillAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillAgentResponse) Reset() {
	*x = KillAgentResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAgentResponse) ProtoMessage() {}

func (x *KillAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAgentResponse.ProtoReflect.Descriptor instead.
func (*KillAgentResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *KillAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListSpawnedAgentsRequest requests list of spawned agents
type ListSpawnedAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpawnedAgentsRequest) Reset() {
	*x = ListSpawnedAgentsRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpawnedAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpawnedAgentsRequest) ProtoMessage() {}

func (x *ListSpawnedAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpawnedAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListSpawnedAgentsRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{18}
}

// ListSpawnedAgentsResponse returns spawned agents
type ListSpawnedAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*SpawnedAgentInfo    `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpawnedAgentsResponse) Reset() {
	*x = ListSpawnedAgentsResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpawnedAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpawnedAgentsResponse) ProtoMessage() {}

func (x *ListSpawnedAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpawnedAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListSpawnedAgentsResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *ListSpawnedAgentsResponse) GetAgents() []*SpawnedAgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// RespawnAgentRequest requests restarting claude in a dead agent pane
type RespawnAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnAgentRequest) Reset() {
	*x = RespawnAgentRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnAgentRequest) ProtoMessage() {}

func (x *RespawnAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnAgentRequest.ProtoReflect.Descriptor instead.
func (*RespawnAgentRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *RespawnAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// RespawnAgentResponse confirms respawn
type RespawnAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnAgentResponse) Reset() {
	*x = RespawnAgentResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnAgentResponse) ProtoMessage() {}

func (x *RespawnAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnAgentResponse.ProtoReflect.Descriptor instead.
func (*RespawnAgentResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *RespawnAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RespawnAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListWorktreesRequest requests list of worktrees
type ListWorktreesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesRequest) Reset() {
	*x = ListWorktreesRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesRequest) ProtoMessage() {}

func (x *ListWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesRequest.ProtoReflect.Descriptor instead.
func (*ListWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{22}
}

// ListWorktreesResponse returns worktree info
type ListWorktreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worktrees     []*WorktreeInfo        `protobuf:"bytes,1,rep,name=worktrees,proto3" json:"worktrees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorktreesResponse) Reset() {
	*x = ListWorktreesResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorktreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorktreesResponse) ProtoMessage() {}

func (x *ListWorktreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorktreesResponse.ProtoReflect.Descriptor instead.
func (*ListWorktreesResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *ListWorktreesResponse) GetWorktrees() []*WorktreeInfo {
	if x != nil {
		return x.Worktrees
	}
	return nil
}

// WorktreeInfo describes a git worktree
type WorktreeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorktreeInfo) Reset() {
	*x = WorktreeInfo{}
	mi := &file_map_v1_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorktreeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorktreeInfo) ProtoMessage() {}

func (x *WorktreeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorktreeInfo.ProtoReflect.Descriptor instead.
func (*WorktreeInfo) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *WorktreeInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorktreeInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorktreeInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *WorktreeInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CleanupWorktreesRequest requests worktree cleanup
type CleanupWorktreesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific agent ID to cleanup (empty = all orphaned)
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Remove all worktrees
	All           bool `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupWorktreesRequest) Reset() {
	*x = CleanupWorktreesRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupWorktreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupWorktreesRequest) ProtoMessage() {}

func (x *CleanupWorktreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupWorktreesRequest.ProtoReflect.Descriptor instead.
func (*CleanupWorktreesRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *CleanupWorktreesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CleanupWorktreesRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

// CleanupWorktreesResponse confirms cleanup
type CleanupWorktreesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemovedCount  int32                  `protobuf:"varint,1,opt,name=removed_count,json=removedCount,proto3" json:"removed_count,omitempty"`
	RemovedPaths  []string               `protobuf:"bytes,2,rep,name=removed_paths,json=removedPaths,proto3" json:"removed_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupWorktreesResponse) Reset() {
	*x = CleanupWorktreesResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupWorktreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupWorktreesResponse) ProtoMessage() {}

func (x *CleanupWorktreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupWorktreesResponse.ProtoReflect.Descriptor instead.
func (*CleanupWorktreesResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *CleanupWorktreesResponse) GetRemovedCount() int32 {
	if x != nil {
		return x.RemovedCount
	}
	return 0
}

func (x *CleanupWorktreesResponse) GetRemovedPaths() []string {
	if x != nil {
		return x.RemovedPaths
	}
	return nil
}

// RequestInputRequest signals that an agent needs user input
type RequestInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInputRequest) Reset() {
	*x = RequestInputRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInputRequest) ProtoMessage() {}

func (x *RequestInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInputRequest.ProtoReflect.Descriptor instead.
func (*RequestInputRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *RequestInputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RequestInputRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

// RequestInputResponse confirms the input request was processed
type RequestInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInputResponse) Reset() {
	*x = RequestInputResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInputResponse) ProtoMessage() {}

func (x *RequestInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInputResponse.ProtoReflect.Descriptor instead.
func (*RequestInputResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *RequestInputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RequestInputResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetCurrentTaskRequest looks up the task for a working directory
type GetCurrentTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkingDirectory string                 `protobuf:"bytes,1,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCurrentTaskRequest) Reset() {
	*x = GetCurrentTaskRequest{}
	mi := &file_map_v1_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTaskRequest) ProtoMessage() {}

func (x *GetCurrentTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTaskRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentTaskRequest) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *GetCurrentTaskRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

// GetCurrentTaskResponse returns the task for the working directory
type GetCurrentTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentTaskResponse) Reset() {
	*x = GetCurrentTaskResponse{}
	mi := &file_map_v1_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentTaskResponse) ProtoMessage() {}

func (x *GetCurrentTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_v1_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentTaskResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentTaskResponse) Descriptor() ([]byte, []int) {
	return file_map_v1_daemon_proto_rawDescGZIP(), []int{30}
}

func (x *GetCurrentTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_map_v1_daemon_proto protoreflect.FileDescriptor

const file_map_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x13map/v1/daemon.proto\x12\x06map.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12map/v1/types.proto\"\xf2\x01\n" +
	"\x11SubmitTaskRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1f\n" +
	"\vscope_paths\x18\x02 \x03(\tR\n" +
	"scopePaths\x12&\n" +
	"\x0ftarget_agent_id\x18\x03 \x01(\tR\rtargetAgentId\x12!\n" +
	"\fgithub_owner\x18\x04 \x01(\tR\vgithubOwner\x12\x1f\n" +
	"\vgithub_repo\x18\x05 \x01(\tR\n" +
	"githubRepo\x12.\n" +
	"\x13github_issue_number\x18\x06 \x01(\x05R\x11githubIssueNumber\"6\n" +
	"\x12SubmitTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.map.v1.TaskR\x04task\"\x84\x01\n" +
	"\x10ListTasksRequest\x127\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x12.map.v1.TaskStatusR\fstatusFilter\x12!\n" +
	"\fagent_filter\x18\x02 \x01(\tR\vagentFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"7\n" +
	"\x11ListTasksResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.map.v1.TaskR\x05tasks\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"3\n" +
	"\x0fGetTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.map.v1.TaskR\x04task\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"6\n" +
	"\x12CancelTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.map.v1.TaskR\x04task\"'\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10GetStatusRequest\"\xdb\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12)\n" +
	"\x10connected_agents\x18\x03 \x01(\x05R\x0fconnectedAgents\x12#\n" +
	"\rpending_tasks\x18\x04 \x01(\x05R\fpendingTasks\x12!\n" +
	"\factive_tasks\x18\x05 \x01(\x05R\vactiveTasks\"\x8c\x01\n" +
	"\x12WatchEventsRequest\x122\n" +
	"\vtype_filter\x18\x01 \x03(\x0e2\x11.map.v1.EventTypeR\n" +
	"typeFilter\x12!\n" +
	"\fagent_filter\x18\x02 \x01(\tR\vagentFilter\x12\x1f\n" +
	"\vtask_filter\x18\x03 \x01(\tR\n" +
	"taskFilter\"\xe7\x01\n" +
	"\x11SpawnAgentRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12!\n" +
	"\fuse_worktree\x18\x03 \x01(\bR\vuseWorktree\x12\x1f\n" +
	"\vname_prefix\x18\x04 \x01(\tR\n" +
	"namePrefix\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x06 \x01(\tR\tagentType\x12)\n" +
	"\x10skip_permissions\x18\a \x01(\bR\x0fskipPermissions\"F\n" +
	"\x12SpawnAgentResponse\x120\n" +
	"\x06agents\x18\x01 \x03(\v2\x18.map.v1.SpawnedAgentInfoR\x06agents\"\xf1\x01\n" +
	"\x10SpawnedAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\rworktree_path\x18\x02 \x01(\tR\fworktreePath\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\blog_file\x18\x06 \x01(\tR\alogFile\x12\x1d\n" +
	"\n" +
	"agent_type\x18\a \x01(\tR\tagentType\"C\n" +
	"\x10KillAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"G\n" +
	"\x11KillAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\x18ListSpawnedAgentsRequest\"M\n" +
	"\x19ListSpawnedAgentsResponse\x120\n" +
	"\x06agents\x18\x01 \x03(\v2\x18.map.v1.SpawnedAgentInfoR\x06agents\"0\n" +
	"\x13RespawnAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"J\n" +
	"\x14RespawnAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14ListWorktreesRequest\"K\n" +
	"\x15ListWorktreesResponse\x122\n" +
	"\tworktrees\x18\x01 \x03(\v2\x14.map.v1.WorktreeInfoR\tworktrees\"\x90\x01\n" +
	"\fWorktreeInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"F\n" +
	"\x17CleanupWorktreesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\"d\n" +
	"\x18CleanupWorktreesResponse\x12#\n" +
	"\rremoved_count\x18\x01 \x01(\x05R\fremovedCount\x12#\n" +
	"\rremoved_paths\x18\x02 \x03(\tR\fremovedPaths\"J\n" +
	"\x13RequestInputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"J\n" +
	"\x14RequestInputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x15GetCurrentTaskRequest\x12+\n" +
	"\x11working_directory\x18\x01 \x01(\tR\x10workingDirectory\":\n" +
	"\x16GetCurrentTaskResponse\x12 \n" +
	"\x04task\x18\x01 \x01(\v2\f.map.v1.TaskR\x04task2\xc1\b\n" +
	"\rDaemonService\x12C\n" +
	"\n" +
	"SubmitTask\x12\x19.map.v1.SubmitTaskRequest\x1a\x1a.map.v1.SubmitTaskResponse\x12@\n" +
	"\tListTasks\x12\x18.map.v1.ListTasksRequest\x1a\x19.map.v1.ListTasksResponse\x12:\n" +
	"\aGetTask\x12\x16.map.v1.GetTaskRequest\x1a\x17.map.v1.GetTaskResponse\x12C\n" +
	"\n" +
	"CancelTask\x12\x19.map.v1.CancelTaskRequest\x1a\x1a.map.v1.CancelTaskResponse\x12I\n" +
	"\fRequestInput\x12\x1b.map.v1.RequestInputRequest\x1a\x1c.map.v1.RequestInputResponse\x12O\n" +
	"\x0eGetCurrentTask\x12\x1d.map.v1.GetCurrentTaskRequest\x1a\x1e.map.v1.GetCurrentTaskResponse\x12=\n" +
	"\bShutdown\x12\x17.map.v1.ShutdownRequest\x1a\x18.map.v1.ShutdownResponse\x12@\n" +
	"\tGetStatus\x12\x18.map.v1.GetStatusRequest\x1a\x19.map.v1.GetStatusResponse\x12:\n" +
	"\vWatchEvents\x12\x1a.map.v1.WatchEventsRequest\x1a\r.map.v1.Event0\x01\x12C\n" +
	"\n" +
	"SpawnAgent\x12\x19.map.v1.SpawnAgentRequest\x1a\x1a.map.v1.SpawnAgentResponse\x12@\n" +
	"\tKillAgent\x12\x18.map.v1.KillAgentRequest\x1a\x19.map.v1.KillAgentResponse\x12X\n" +
	"\x11ListSpawnedAgents\x12 .map.v1.ListSpawnedAgentsRequest\x1a!.map.v1.ListSpawnedAgentsResponse\x12I\n" +
	"\fRespawnAgent\x12\x1b.map.v1.RespawnAgentRequest\x1a\x1c.map.v1.RespawnAgentResponse\x12L\n" +
	"\rListWorktrees\x12\x1c.map.v1.ListWorktreesRequest\x1a\x1d.map.v1.ListWorktreesResponse\x12U\n" +
	"\x10CleanupWorktrees\x12\x1f.map.v1.CleanupWorktreesRequest\x1a .map.v1.CleanupWorktreesResponseB1Z/github.com/pmarsceill/mapcli/proto/map/v1;mapv1b\x06proto3"

var (
	file_map_v1_daemon_proto_rawDescOnce sync.Once
	file_map_v1_daemon_proto_rawDescData []byte
)

func file_map_v1_daemon_proto_rawDescGZIP() []byte {
	file_map_v1_daemon_proto_rawDescOnce.Do(func() {
		file_map_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_map_v1_daemon_proto_rawDesc), len(file_map_v1_daemon_proto_rawDesc)))
	})
	return file_map_v1_daemon_proto_rawDescData
}

var file_map_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_map_v1_daemon_proto_goTypes = []any{
	(*SubmitTaskRequest)(nil),         // 0: map.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),        // 1: map.v1.SubmitTaskResponse
	(*ListTasksRequest)(nil),          // 2: map.v1.ListTasksRequest
	(*ListTasksResponse)(nil),         // 3: map.v1.ListTasksResponse
	(*GetTaskRequest)(nil),            // 4: map.v1.GetTaskRequest
	(*GetTaskResponse)(nil),           // 5: map.v1.GetTaskResponse
	(*CancelTaskRequest)(nil),         // 6: map.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),        // 7: map.v1.CancelTaskResponse
	(*ShutdownRequest)(nil),           // 8: map.v1.ShutdownRequest
	(*ShutdownResponse)(nil),          // 9: map.v1.ShutdownResponse
	(*GetStatusRequest)(nil),          // 10: map.v1.GetStatusRequest
	(*GetStatusResponse)(nil),         // 11: map.v1.GetStatusResponse
	(*WatchEventsRequest)(nil),        // 12: map.v1.WatchEventsRequest
	(*SpawnAgentRequest)(nil),         // 13: map.v1.SpawnAgentRequest
	(*SpawnAgentResponse)(nil),        // 14: map.v1.SpawnAgentResponse
	(*SpawnedAgentInfo)(nil),          // 15: map.v1.SpawnedAgentInfo
	(*KillAgentRequest)(nil),          // 16: map.v1.KillAgentRequest
	(*KillAgentResponse)(nil),         // 17: map.v1.KillAgentResponse
	(*ListSpawnedAgentsRequest)(nil),  // 18: map.v1.ListSpawnedAgentsRequest
	(*ListSpawnedAgentsResponse)(nil), // 19: map.v1.ListSpawnedAgentsResponse
	(*RespawnAgentRequest)(nil),       // 20: map.v1.RespawnAgentRequest
	(*RespawnAgentResponse)(nil),      // 21: map.v1.RespawnAgentResponse
	(*ListWorktreesRequest)(nil),      // 22: map.v1.ListWorktreesRequest
	(*ListWorktreesResponse)(nil),     // 23: map.v1.ListWorktreesResponse
	(*WorktreeInfo)(nil),              // 24: map.v1.WorktreeInfo
	(*CleanupWorktreesRequest)(nil),   // 25: map.v1.CleanupWorktreesRequest
	(*CleanupWorktreesResponse)(nil),  // 26: map.v1.CleanupWorktreesResponse
	(*RequestInputRequest)(nil),       // 27: map.v1.RequestInputRequest
	(*RequestInputResponse)(nil),      // 28: map.v1.RequestInputResponse
	(*GetCurrentTaskRequest)(nil),     // 29: map.v1.GetCurrentTaskRequest
	(*GetCurrentTaskResponse)(nil),    // 30: map.v1.GetCurrentTaskResponse
	(*Task)(nil),                      // 31: map.v1.Task
	(TaskStatus)(0),                   // 32: map.v1.TaskStatus
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
	(EventType)(0),                    // 34: map.v1.EventType
	(*Event)(nil),                     // 35: map.v1.Event
}
var file_map_v1_daemon_proto_depIdxs = []int32{
	31, // 0: map.v1.SubmitTaskResponse.task:type_name -> map.v1.Task
	32, // 1: map.v1.ListTasksRequest.status_filter:type_name -> map.v1.TaskStatus
	31, // 2: map.v1.ListTasksResponse.tasks:type_name -> map.v1.Task
	31, // 3: map.v1.GetTaskResponse.task:type_name -> map.v1.Task
	31, // 4: map.v1.CancelTaskResponse.task:type_name -> map.v1.Task
	33, // 5: map.v1.GetStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	34, // 6: map.v1.WatchEventsRequest.type_filter:type_name -> map.v1.EventType
	15, // 7: map.v1.SpawnAgentResponse.agents:type_name -> map.v1.SpawnedAgentInfo
	33, // 8: map.v1.SpawnedAgentInfo.created_at:type_name -> google.protobuf.Timestamp
	15, // 9: map.v1.ListSpawnedAgentsResponse.agents:type_name -> map.v1.SpawnedAgentInfo
	24, // 10: map.v1.ListWorktreesResponse.worktrees:type_name -> map.v1.WorktreeInfo
	33, // 11: map.v1.WorktreeInfo.created_at:type_name -> google.protobuf.Timestamp
	31, // 12: map.v1.GetCurrentTaskResponse.task:type_name -> map.v1.Task
	0,  // 13: map.v1.DaemonService.SubmitTask:input_type -> map.v1.SubmitTaskRequest
	2,  // 14: map.v1.DaemonService.ListTasks:input_type -> map.v1.ListTasksRequest
	4,  // 15: map.v1.DaemonService.GetTask:input_type -> map.v1.GetTaskRequest
	6,  // 16: map.v1.DaemonService.CancelTask:input_type -> map.v1.CancelTaskRequest
	27, // 17: map.v1.DaemonService.RequestInput:input_type -> map.v1.RequestInputRequest
	29, // 18: map.v1.DaemonService.GetCurrentTask:input_type -> map.v1.GetCurrentTaskRequest
	8,  // 19: map.v1.DaemonService.Shutdown:input_type -> map.v1.ShutdownRequest
	10, // 20: map.v1.DaemonService.GetStatus:input_type -> map.v1.GetStatusRequest
	12, // 21: map.v1.DaemonService.WatchEvents:input_type -> map.v1.WatchEventsRequest
	13, // 22: map.v1.DaemonService.SpawnAgent:input_type -> map.v1.SpawnAgentRequest
	16, // 23: map.v1.DaemonService.KillAgent:input_type -> map.v1.KillAgentRequest
	18, // 24: map.v1.DaemonService.ListSpawnedAgents:input_type -> map.v1.ListSpawnedAgentsRequest
	20, // 25: map.v1.DaemonService.RespawnAgent:input_type -> map.v1.RespawnAgentRequest
	22, // 26: map.v1.DaemonService.ListWorktrees:input_type -> map.v1.ListWorktreesRequest
	25, // 27: map.v1.DaemonService.CleanupWorktrees:input_type -> map.v1.CleanupWorktreesRequest
	1,  // 28: map.v1.DaemonService.SubmitTask:output_type -> map.v1.SubmitTaskResponse
	3,  // 29: map.v1.DaemonService.ListTasks:output_type -> map.v1.ListTasksResponse
	5,  // 30: map.v1.DaemonService.GetTask:output_type -> map.v1.GetTaskResponse
	7,  // 31: map.v1.DaemonService.CancelTask:output_type -> map.v1.CancelTaskResponse
	28, // 32: map.v1.DaemonService.RequestInput:output_type -> map.v1.RequestInputResponse
	30, // 33: map.v1.DaemonService.GetCurrentTask:output_type -> map.v1.GetCurrentTaskResponse
	9,  // 34: map.v1.DaemonService.Shutdown:output_type -> map.v1.ShutdownResponse
	11, // 35: map.v1.DaemonService.GetStatus:output_type -> map.v1.GetStatusResponse
	35, // 36: map.v1.DaemonService.WatchEvents:output_type -> map.v1.Event
	14, // 37: map.v1.DaemonService.SpawnAgent:output_type -> map.v1.SpawnAgentResponse
	17, // 38: map.v1.DaemonService.KillAgent:output_type -> map.v1.KillAgentResponse
	19, // 39: map.v1.DaemonService.ListSpawnedAgents:output_type -> map.v1.ListSpawnedAgentsResponse
	21, // 40: map.v1.DaemonService.RespawnAgent:output_type -> map.v1.RespawnAgentResponse
	23, // 41: map.v1.DaemonService.ListWorktrees:output_type -> map.v1.ListWorktreesResponse
	26, // 42: map.v1.DaemonService.CleanupWorktrees:output_type -> map.v1.CleanupWorktreesResponse
	28, // [28:43] is the sub-list for method output_type
	13, // [13:28] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_map_v1_daemon_proto_init() }
func file_map_v1_daemon_proto_init() {
	if File_map_v1_daemon_proto != nil {
		return
	}
	file_map_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_map_v1_daemon_proto_rawDesc), len(file_map_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_map_v1_daemon_proto_goTypes,
		DependencyIndexes: file_map_v1_daemon_proto_depIdxs,
		MessageInfos:      file_map_v1_daemon_proto_msgTypes,
	}.Build()
	File_map_v1_daemon_proto = out.File
	file_map_v1_daemon_proto_goTypes = nil
	file_map_v1_daemon_proto_depIdxs = nil
}
