// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: map/v1/daemon.proto

package mapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_SubmitTask_FullMethodName        = "/map.v1.DaemonService/SubmitTask"
	DaemonService_ListTasks_FullMethodName         = "/map.v1.DaemonService/ListTasks"
	DaemonService_GetTask_FullMethodName           = "/map.v1.DaemonService/GetTask"
	DaemonService_CancelTask_FullMethodName        = "/map.v1.DaemonService/CancelTask"
	DaemonService_RequestInput_FullMethodName      = "/map.v1.DaemonService/RequestInput"
	DaemonService_GetCurrentTask_FullMethodName    = "/map.v1.DaemonService/GetCurrentTask"
	DaemonService_Shutdown_FullMethodName          = "/map.v1.DaemonService/Shutdown"
	DaemonService_GetStatus_FullMethodName         = "/map.v1.DaemonService/GetStatus"
	DaemonService_WatchEvents_FullMethodName       = "/map.v1.DaemonService/WatchEvents"
	DaemonService_SpawnAgent_FullMethodName        = "/map.v1.DaemonService/SpawnAgent"
	DaemonService_KillAgent_FullMethodName         = "/map.v1.DaemonService/KillAgent"
	DaemonService_ListSpawnedAgents_FullMethodName = "/map.v1.DaemonService/ListSpawnedAgents"
	DaemonService_RespawnAgent_FullMethodName      = "/map.v1.DaemonService/RespawnAgent"
	DaemonService_ListWorktrees_FullMethodName     = "/map.v1.DaemonService/ListWorktrees"
	DaemonService_CleanupWorktrees_FullMethodName  = "/map.v1.DaemonService/CleanupWorktrees"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService is the API exposed by mapd for CLI clients
type DaemonServiceClient interface {
	// Task management
	SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	RequestInput(ctx context.Context, in *RequestInputRequest, opts ...grpc.CallOption) (*RequestInputResponse, error)
	GetCurrentTask(ctx context.Context, in *GetCurrentTaskRequest, opts ...grpc.CallOption) (*GetCurrentTaskResponse, error)
	// Daemon control
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Real-time event streaming
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Spawned agent management
	SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error)
	KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*KillAgentResponse, error)
	ListSpawnedAgents(ctx context.Context, in *ListSpawnedAgentsRequest, opts ...grpc.CallOption) (*ListSpawnedAgentsResponse, error)
	RespawnAgent(ctx context.Context, in *RespawnAgentRequest, opts ...grpc.CallOption) (*RespawnAgentResponse, error)
	// Worktree management
	ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error)
	CleanupWorktrees(ctx context.Context, in *CleanupWorktreesRequest, opts ...grpc.CallOption) (*CleanupWorktreesResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskResponse)
	err := c.cc.Invoke(ctx, DaemonService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, DaemonService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RequestInput(ctx context.Context, in *RequestInputRequest, opts ...grpc.CallOption) (*RequestInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestInputResponse)
	err := c.cc.Invoke(ctx, DaemonService_RequestInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetCurrentTask(ctx context.Context, in *GetCurrentTaskRequest, opts ...grpc.CallOption) (*GetCurrentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentTaskResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetCurrentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *daemonServiceClient) SpawnAgent(ctx context.Context, in *SpawnAgentRequest, opts ...grpc.CallOption) (*SpawnAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnAgentResponse)
	err := c.cc.Invoke(ctx, DaemonService_SpawnAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) KillAgent(ctx context.Context, in *KillAgentRequest, opts ...grpc.CallOption) (*KillAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillAgentResponse)
	err := c.cc.Invoke(ctx, DaemonService_KillAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListSpawnedAgents(ctx context.Context, in *ListSpawnedAgentsRequest, opts ...grpc.CallOption) (*ListSpawnedAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpawnedAgentsResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListSpawnedAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RespawnAgent(ctx context.Context, in *RespawnAgentRequest, opts ...grpc.CallOption) (*RespawnAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespawnAgentResponse)
	err := c.cc.Invoke(ctx, DaemonService_RespawnAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListWorktrees(ctx context.Context, in *ListWorktreesRequest, opts ...grpc.CallOption) (*ListWorktreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorktreesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CleanupWorktrees(ctx context.Context, in *CleanupWorktreesRequest, opts ...grpc.CallOption) (*CleanupWorktreesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupWorktreesResponse)
	err := c.cc.Invoke(ctx, DaemonService_CleanupWorktrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService is the API exposed by mapd for CLI clients
type DaemonServiceServer interface {
	// Task management
	SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	RequestInput(context.Context, *RequestInputRequest) (*RequestInputResponse, error)
	GetCurrentTask(context.Context, *GetCurrentTaskRequest) (*GetCurrentTaskResponse, error)
	// Daemon control
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Real-time event streaming
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error
	// Spawned agent management
	SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error)
	KillAgent(context.Context, *KillAgentRequest) (*KillAgentResponse, error)
	ListSpawnedAgents(context.Context, *ListSpawnedAgentsRequest) (*ListSpawnedAgentsResponse, error)
	RespawnAgent(context.Context, *RespawnAgentRequest) (*RespawnAgentResponse, error)
	// Worktree management
	ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error)
	CleanupWorktrees(context.Context, *CleanupWorktreesRequest) (*CleanupWorktreesResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedDaemonServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedDaemonServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedDaemonServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedDaemonServiceServer) RequestInput(context.Context, *RequestInputRequest) (*RequestInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestInput not implemented")
}
func (UnimplementedDaemonServiceServer) GetCurrentTask(context.Context, *GetCurrentTaskRequest) (*GetCurrentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentTask not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedDaemonServiceServer) SpawnAgent(context.Context, *SpawnAgentRequest) (*SpawnAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SpawnAgent not implemented")
}
func (UnimplementedDaemonServiceServer) KillAgent(context.Context, *KillAgentRequest) (*KillAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillAgent not implemented")
}
func (UnimplementedDaemonServiceServer) ListSpawnedAgents(context.Context, *ListSpawnedAgentsRequest) (*ListSpawnedAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpawnedAgents not implemented")
}
func (UnimplementedDaemonServiceServer) RespawnAgent(context.Context, *RespawnAgentRequest) (*RespawnAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespawnAgent not implemented")
}
func (UnimplementedDaemonServiceServer) ListWorktrees(context.Context, *ListWorktreesRequest) (*ListWorktreesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorktrees not implemented")
}
func (UnimplementedDaemonServiceServer) CleanupWorktrees(context.Context, *CleanupWorktreesRequest) (*CleanupWorktreesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupWorktrees not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SubmitTask(ctx, req.(*SubmitTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RequestInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RequestInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RequestInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RequestInput(ctx, req.(*RequestInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetCurrentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetCurrentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetCurrentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetCurrentTask(ctx, req.(*GetCurrentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _DaemonService_SpawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SpawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SpawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SpawnAgent(ctx, req.(*SpawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_KillAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).KillAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_KillAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).KillAgent(ctx, req.(*KillAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListSpawnedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpawnedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListSpawnedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListSpawnedAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListSpawnedAgents(ctx, req.(*ListSpawnedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RespawnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespawnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RespawnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RespawnAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RespawnAgent(ctx, req.(*RespawnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListWorktrees(ctx, req.(*ListWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CleanupWorktrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupWorktreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CleanupWorktrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CleanupWorktrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CleanupWorktrees(ctx, req.(*CleanupWorktreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "map.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _DaemonService_SubmitTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _DaemonService_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _DaemonService_GetTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _DaemonService_CancelTask_Handler,
		},
		{
			MethodName: "RequestInput",
			Handler:    _DaemonService_RequestInput_Handler,
		},
		{
			MethodName: "GetCurrentTask",
			Handler:    _DaemonService_GetCurrentTask_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
		{
			MethodName: "SpawnAgent",
			Handler:    _DaemonService_SpawnAgent_Handler,
		},
		{
			MethodName: "KillAgent",
			Handler:    _DaemonService_KillAgent_Handler,
		},
		{
			MethodName: "ListSpawnedAgents",
			Handler:    _DaemonService_ListSpawnedAgents_Handler,
		},
		{
			MethodName: "RespawnAgent",
			Handler:    _DaemonService_RespawnAgent_Handler,
		},
		{
			MethodName: "ListWorktrees",
			Handler:    _DaemonService_ListWorktrees_Handler,
		},
		{
			MethodName: "CleanupWorktrees",
			Handler:    _DaemonService_CleanupWorktrees_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _DaemonService_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "map/v1/daemon.proto",
}
